# Generated by Django 3.2.8 on 2021-10-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211021_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
